// JavaScript Document

var aData = {
	intelligent:{
		title:"智能硬件",
		name:"小米路由器3",
		price:"149元",
		desc:"四天线设计，更安全更稳定",
		status:["免邮件","有赠品"],
		image:[
			"images/znyj/znyj1.jpg",
			"images/znyj/znyj2.jpg",
			"images/znyj/znyj3.jpg",
			"images/znyj/znyj4.jpg",
		]
	},
	match:{
		title:["搭配","配件"],
		name:"小米路由器3",
		price:"149元",
		cmt:"18.7万人评价",
		contents:{
			dapei:["热门","耳机音箱","电源","电池存储卡"],
			peijian:["热门","保护膜","贴膜","其他配件"]
		},
		evaluate:"音质非常好，很震撼！！美美美！",
		status:["免邮件","有赠品"],
		image:[
			"images/dp/dp1.jpg",
			"images/dp/dp2.jpg",
			"images/dp/dp3.jpg",
			"images/dp/dp4.jpg",
			"images/dp/dp5.jpg",
			"images/dp/dp6.jpg",
			"images/dp/dp7.jpg",
			"images/dp/dp8.jpg"
		]
	},
	surrounding:{
		title:"周边",
		contents:["热门","服装","米兔","生活周边","箱包"],
		status:["免邮件","有赠品"],
		name:"小米路由器3",
		price:"149元",
		desc:"四天线设计，更安全更稳定",
		introL:{
			name:"小米小钢炮",
			price:"79元"
		},
		image:[
			"images/zb/zb1.jpg",
			"images/zb/zb2.jpg",
			"images/zb/zb3.jpg",
			"images/zb/zb4.jpg",
			"images/zb/zb5.jpg",
			"images/zb/zb6.jpg",
			"images/zb/zb7.jpg",
			"images/zb/zb0.jpg",
		]
	},
}
